# .github/workflows/docker-publish.yml
name: Docker Publish on Release

on:
  release:
    types: [published] # Trigger when a release is published

permissions:
  contents: read # To checkout the code
  packages: write # To push packages to GHCR

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU # For multi-platform builds (optional but recommended)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Image name: ghcr.io/OWNER/REPO
          tags: |
            type=semver,pattern={{version}} # Tag with the release version (e.g., 1.2.3)
            type=semver,pattern={{major}}.{{minor}} # Tag with major.minor (e.g., 1.2)
            type=semver,pattern={{major}} # Tag with major (e.g., 1)
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }} # Tag as latest if not a prerelease

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 
